<a href="https://colab.research.google.com/github/aurabinda90-dev/CFD-in-Python/blob/main/Step_6_Array_Operations_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Step 6: Array Operations with NumPy

In [ ]:
import numpy as np
u = np.array((0,1,2,3,4,5))
u1 = np.zeros(len(u)-1)
#for i in range(len(u)):  #this outputs 0,1,2,3,4,5
#for i in range(1, len(u)): # this outputs 1,2,3,4,5
#    print(i)

for i in range(1, len(u)):
    u1[i-1] = u[i] - u[i-1]

u1

array([1., 1., 1., 1., 1.])

In [ ]:
u[1:] - u[0:-1]

array([1, 1, 1, 1, 1])

In [ ]:
print(u[1:])
print(u[0:-1])

[1 2 3 4 5]
[0 1 2 3 4]


In [ ]:
nx = 81
ny = 81
nt = 100
c = 1
dx = 2 / (nx - 1)
dy = 2 / (ny - 1)
sigma = .2
dt = sigma * dx

x = np.linspace(0, 2, nx)
y = np.linspace(0, 2, ny)

u = np.ones((nx, ny)) ##create a 1xn vector of 1's
un = np.ones((nx, ny))

###Assign initial conditions

u[int(.5 / dx): int(1 / dx + 1), int(.5 / dy):int(1 / dy + 1)] = 2

In [ ]:
%%timeit
u = np.ones((nx, ny))
u[int(.5 / dx): int(1 / dx + 1), int(.5 / dy):int(1 / dy + 1)] = 2

for n in range(nt):
    un = u.copy()
    row, col = u.shape
    for i in range(1, row):
        for j in range(1, col):
            u[i,j] = (un[i,j] - (c * dt / dx * (un[i,j] - un[i-1,j])) -
                                (c * dt / dy * (un[i,j] - un[i,j-1])))
            u[0, :] = 1
            u[:, 0] = 1


2.14 s ± 664 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
u = np.ones((nx, ny))
u[int(.5 / dx): int(1 / dx + 1), int(.5 / dy):int(1 / dy + 1)] = 2

for n in range(nt + 1): ##loop across number of time steps
    un = u.copy()
    u[1:, 1:] = (un[1:, 1:] - (c * dt / dx * (un[1:, 1:] - un[0:-1, 1:])) -
                              (c * dt / dy * (un[1:, 1:] - un[1:, 0:-1])))
    u[0, :] = 1
    u[:, 0] = 1

4.94 ms ± 392 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
def simpleadd(a, b):
    return a + b

In [ ]:
simpleadd(3, 4)

7